import * as crypto from 'crypto'

const adjectiveList : string[] = ["Adorable","Adventurous","Aggressive","Agreeable","Alert","Alive","Amused","Angry","Annoyed","Annoying","Anxious","Arrogant","Ashamed","Attractive","Average","Awful","Bad","Beautiful","Better","Bewildered","Black","Bloody","Blue","Blushing","Bored","Brainy","Brave","Breakable","Bright","Busy","Calm","Careful","Cautious","Charming","Cheerful","Clean","Clear","Clever","Cloudy","Clumsy","Colorful","Combative","Comfortable","Concerned","Condemned","Confused","Cooperative","Courageous","Crazy","Creepy","Crowded","Cruel","Curious","Cute","Dangerous","Dark","Dead","Defeated","Defiant","Delightful","Depressed","Determined","Different","Difficult","Disgusted","Distinct","Disturbed","Dizzy","Doubtful","Drab","Dull","Eager","Easy","Elated","Elegant","Embarrassed","Enchanting","Encouraging","Energetic","Enthusiastic","Envious","Evil","Excited","Expensive","Exuberant","Fair","Faithful","Famous","Fancy","Fantastic","Fierce","Filthy","Fine","Foolish","Fragile","Frail","Frantic","Friendly","Frightened","Funny","Gentle","Gifted","Glamorous","Gleaming","Glorious","Good","Gorgeous","Graceful","Grieving","Grotesque","Grumpy","Handsome","Happy","Healthy","Helpful","Helpless","Hilarious","Homeless","Homely","Horrible","Hungry","Hurt","Ill","Important","Impossible","Inexpensive","Innocent","Inquisitive","Itchy","Jealous","Jittery","Jolly","Joyous","Kind","Lazy","Light","Lively","Lonely","Long","Lovely","Lucky","Magnificent","Misty","Modern","Motionless","Muddy","Mushy","Mysterious","Nasty","Naughty","Nervous","Nice","Nutty","Obedient","Obnoxious","Odd","Open","Outrageous","Outstanding","Panicky","Perfect","Plain","Pleasant","Poised","Poor","Powerful","Precious","Prickly","Proud","Putrid","Puzzled","Quaint","Real","Relieved","Repulsive","Rich","Scary","Selfish","Shiny","Shy","Silly","Sleepy","Smiling","Smoggy","Sore","Sparkling","Splendid","Spotless","Stormy","Strange","Stupid","Successful","Super","Talented","Tame","Tasty","Tender","Tense","Terrible","Thankful","Thoughtful","Thoughtless","Tired","Tough","Troubled","Ugliest","Ugly","Uninterested","Unsightly","Unusual","Upset","Uptight","Vast","Victorious","Vivacious","Wandering","Weary","Wicked","Wild","Witty","Worried","Worrisome","Wrong","Zany","Zealous"]

const nounList : string[] = ["Actor","Afternoon","Airport","Ambulance","Animal","Answer","Apple","Army","Balloon","Banana","Battery","Beach","Beard","Bed","Boy","Branch","Breakfast","Brother","Camera","Candle","Car","Caravan","Carpet","Cartoon","Church","Crayon","Crowd","Daughter","Death","Diamond","Dinner","Disease","Doctor","Dog","Dream","Dress","Easter","Egg","Eggplant","Elephant","Energy","Engine","Evening","Eye","Family","Fern","Fish","Flag","Flower","Football","Forest","Fountain","France","Furniture","Garage","Garden","Gas","Ghost","Girl","Glass","Gold","Grass","Guitar","Hair","Hamburger","Helicopter","Helmet","Holiday","Honey","Horse","Hospital","House","Hydrogen","Ice","Insect","Insurance","Iron","Island","Jackal","Jelly","Jewellery","Jordan","Juice","Kangaroo","King","Kitchen","Kite","Knife","Lamp","Lawyer","Leather","Library","Lighter","Lion","Lizard","Lock","Lunch","Machine","Magazine","Magician","Market","Match","Microphone","Monkey","Morning","Motorcycle","Nail","Napkin","Needle","Nest","Night","Notebook","Ocean","Oil","Orange","Oxygen","Oyster","Painting","Parrot","Pencil","Piano","Pillow","Pizza","Planet","Plastic","Potato","Queen","Quill","Rain","Rainbow","Raincoat","Refrigerator","Restaurant","River","Rocket","Room","Rose","Sandwich","School","Scooter","Shampoo","Shoe","Soccer","Spoon","Stone","Sugar","Teacher","Telephone","Television","Tent","Toothbrush","Traffic","Train","Truck","Van","Vase","Vegetable","Vulture","Wall","Whale","Window","Wire","Xylophone","Yacht","Yak","Zebra","Zoo"]

export function generate(seed : string) : string {
  const hash = crypto.createHash('sha1')
  const digest = hash.update(seed).digest('hex')

  const adjectiveIndex = parseInt(digest.substring(0, 4), 16) % adjectiveList.length
  const nounIndex = parseInt(digest.substring(4, 8), 16) % nounList.length
  return adjectiveList[adjectiveIndex] + nounList[nounIndex]
}

